disabled_rules:
  # its better to keep todos in code than to loose track of them somewhere else
  - todo
  # conflicts with swiftformat's default
  - trailing_comma
excluded:
  # ignore vendor files, will be removed in the future
  - WireGuardStatusbar/INIParser.swift
  - WireGuardStatusbarHelper/SKQueue.swift
